- name: 기본 시스템 설정
  hosts: web
  become: true
  tasks:
    - name: 모든 패키지 최신화
      ansible.builtin.package:
        name: "*"
        state: latest
    - name: 새 사용자 생성
      ansible.builtin.user:
        name: roger
        state: present
        create_home: true
